### PR TITLE
Fix getRobotPose in melodic

### PR DESCRIPTION
**Pull request by ipa-fez**
The wrong frame was passed to transformPose. Somehow this worked pre-melodic.

### CODE REVIEW

**Comment by corot** [comment]
LGTM; works both on kinetic and melodic, and fixes #100

**Review by spuetz — CHANGES_REQUESTED** [review]
Hmmm, there are some things mixed up. But I'll review the rest tomorrow morning. (In 13 h)

**Review by spuetz — CHANGES_REQUESTED** [review]
We could also improve this by using lookUpTransform in both cases and use the transformation directly by applying it to the pose object, which is a transform object.

**Comment by spuetz** [comment]
@ipa-fez Could you test this? https://github.com/magazino/move_base_flex/tree/fix-melodic-tf I fixed the frame ids of this PR. Thank you!

**Comment by ipa-fez** [comment]
Seems to work fine on melodic @spuetz, thanks for the improvements! I did indeed get fixed frame and target frame mixed up.

**Comment by ipa-fez** [comment]
I pushed the commits to this branch. Feel free to merge.

**Comment by corot** [comment]
hehe  I was just about to merge this

**Pull request merged**
