### PR TITLE
Do not publish path from MBF

### PR DESCRIPTION
**Pull request by corot**
It's published by all planners, afaik.
I also moved the goal_pose to the private node handle, so it comes within MBF namespace

### CODE REVIEW

**Comment by spuetz** [comment]
The plan is published from every planner, yes, shouldn't we add a switch / param for publishing it or not? I mean this breaks the current API a bit. So we should discuss that first.

**Comment by corot** [comment]
> The plan is published from every planner, yes, shouldn't we add a switch / param for publishing it or not? I mean this breaks the current API a bit. So we should discuss that first.

Nope, path was not published on old move_base, if I checked properly

**Comment by spuetz** [comment]
No I mean API change of MBF. So why not having a switch for that using a param for turning it on and off

**Comment by corot** [comment]
mmm... I don't think anyone is using this path... I even noticed by chance that we where publishing it! :see_no_evil:

**Comment by spuetz** [comment]
I would like to keep the publishPlan method in MBF.

**Comment by spuetz** [comment]
Ok, rethought. I'll merge it.

**Pull request merged**
