### PR TITLE
Use stringstream to append enum to message

### PR DESCRIPTION
**Pull request by ipa-fez**
Adding the int to the string literal does pointer arithmetic.

### CODE REVIEW

**Comment by corot** [comment]
lgtm

**Comment by MichaelGrupp** [comment]
Drive-by comment: `std::to_string(int)` if C++11 is used?

**Comment by corot** [comment]
Nop...  as we started development on indigo, we decided not to use C+11.
Probably is time to reconsider that

**Comment by MichaelGrupp** [comment]
Would be cool, 11 is just so much superior IMO.

**Comment by spuetz** [comment]
@MichaelGrupp After #36 merging branch https://github.com/magazino/move_base_flex/tree/feature/concurrency we will switch to c++11 or c++14, since kinetic has the target version c++11 and melodic has c++14. Older versions do not make sens any more. We live in 2018 and the old c++ standard is limiting too much.

**Review by spuetz — APPROVED** [review]
@ipa-fez thank you for the pull request!

**Pull request merged**
